# Generated by Django 4.2.8 on 2023-12-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LmTransformerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_context", models.TextField()),
                ("question_asked", models.TextField()),
                ("predicted_answer", models.TextField()),
            ],
        ),
    ]
