# Generated by Django 4.2.8 on 2023-12-14 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserDetail",
        ),
    ]
