# Generated by Django 4.2.8 on 2023-12-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_user_userdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
