# Generated by Django 4.2.8 on 2023-12-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_userdetail_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
